using Mail.Cli;
using Mail.Compiler;
using Mail.Contracts;
using Mail.Runtime;
using Mail.Runtime.Providers;
using System.Collections.Immutable;
using Xunit;

namespace Mail.Tests;

public class CliRegistrationTests
{
    private static readonly string TokenEchoSource = File.ReadAllText(
        Path.Combine(AppContext.BaseDirectory, "../../../../..", "examples", "token-echo.mail"));

    [Fact]
    public async Task Cli_registration_uses_GenerateTokenTool_not_stub()
    {
        var (plan, _) = MailCompiler.Compile(TokenEchoSource, "token-echo.mail");
        Assert.NotNull(plan);

        // Use the same factory the CLI uses — NOT a manually built registry
        var registry = ToolRegistryFactory.Build(plan, out var tokenTool);

        // Proves the CLI registers GenerateTokenTool, not EchoTool, for GenerateToken
        Assert.NotNull(tokenTool);
        Assert.IsType<GenerateTokenTool>(tokenTool);

        var providers = new ProviderRegistry();
        providers.Register("Sim", new AdaptiveTokenProvider());

        var executor = new WorkflowExecutor(plan, registry, providers, ExecutionLimits.Default);
        var input = new MailSchema("EchoRequest",
            ImmutableDictionary<string, MailValue>.Empty.Add("prompt", new MailString("cli-reg-test")));

        var result = await executor.RunAsync(input, CancellationToken.None);

        Assert.True(result.Succeeded, result.ErrorMessage);

        // Tool was dispatched
        Assert.NotNull(tokenTool.LastToken);
        Assert.Contains(result.Events, e => e.Kind == "tool.started");

        // Token in output matches the one generated by GenerateTokenTool
        var output = Assert.IsType<MailSchema>(result.Output);
        var outputToken = ((MailString)output.Fields["token"]).Value;
        Assert.Equal(tokenTool.LastToken, outputToken);
    }

    [Fact]
    public async Task Cli_verification_fails_when_dispatch_is_skipped()
    {
        var (plan, _) = MailCompiler.Compile(TokenEchoSource, "token-echo.mail");
        Assert.NotNull(plan);

        var registry = ToolRegistryFactory.Build(plan, out var tokenTool);
        Assert.NotNull(tokenTool);

        var providers = new ProviderRegistry();

        // Provider fabricates a token without dispatching the tool
        providers.Register("Sim", new SimulatedModelProvider([
            new ModelResponse(null, """{"token":"fabricated-bypassed-token"}""")
        ]));

        var executor = new WorkflowExecutor(plan, registry, providers, ExecutionLimits.Default);
        var input = new MailSchema("EchoRequest",
            ImmutableDictionary<string, MailValue>.Empty.Add("prompt", new MailString("bypass-test")));

        var result = await executor.RunAsync(input, CancellationToken.None);

        Assert.True(result.Succeeded, result.ErrorMessage); // valid structure

        // CLI verification criteria — both must fail to prove the bypass is detected
        Assert.Null(tokenTool.LastToken);                 // no dispatch
        Assert.DoesNotContain(result.Events, e => e.Kind == "tool.started");

        // The token in the output does NOT match what GenerateTokenTool would have generated
        var output = Assert.IsType<MailSchema>(result.Output);
        var outputToken = ((MailString)output.Fields["token"]).Value;
        Assert.NotEqual(tokenTool.LastToken, outputToken); // mismatch proves broken cycle
    }
}
