<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mail.Contracts\Mail.Contracts.csproj" />
    <ProjectReference Include="..\Mail.Runtime\Mail.Runtime.csproj" />
  </ItemGroup>

</Project>
